// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MVideo.Api.Data;

#nullable disable

namespace MVideo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVideo.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Телевизоры"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Смартфоны"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ноутбуки"
                        });
                });

            modelBuilder.Entity("MVideo.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Samsung Galaxy S25",
                            Sku = "PHONE-001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Apple iPhone 16",
                            Sku = "PHONE-002",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "LG OLED C4",
                            Sku = "TV-001",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Samsung QLED Q80D",
                            Sku = "TV-002",
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Lenovo ThinkPad E14",
                            Sku = "LAPTOP-001",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MVideo.Api.Models.Product", b =>
                {
                    b.HasOne("MVideo.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVideo.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
